import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Sidebar from "@/components/Sidebar";
import HomeLayout from "@/components/HomeLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Clinic App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar />
        <HomeLayout />
      </main>
    </>
  );
}
