import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HomeLayout from "@/src/components/HomeLayout";
import axios from "axios";
const client = axios.create({
  baseURL: "https://api.soowgood.com",
});

export default function Home({ users }) {
  return (
    <>
      <Head>
        <title>Clinic App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HomeLayout users={users} />
      </>
    </>
  );
}

export async function getStaticProps() {
  const response = await client.post("/api/Searches/Provider", {
    UserRole: "Provider",
  });
  return {
    props: {
      users: response.data,
    },
  };
}
